export const PersonalDetailsData = [
  {
    title: "Address",
    icon: "home-outline",
    placeholder: "Flat No., Street Name",
    keyboardType: "default",
    name: "address",
  },
  {
    title: "Land Mark",
    icon: "business-outline",
    placeholder: "Landmark, Locality",
    keyboardType: "default",
    name: "landmark",
  },
  {
    title: "Pincode",
    icon: "location-outline",
    placeholder: "Pincode",
    keyboardType: "number-pad",
    name: "pincode",
  },
  {
    title: "City",
    icon: "business-outline",
    placeholder: "City",
    keyboardType: "default",
    name: "city",
  },
  {
    title: "Country",
    icon: "globe-outline",
    placeholder: "Country",
    keyboardType: "default",
    name: "country",
  },
  {
    title: "Industry",
    icon: "podium-outline",
    placeholder: "Industry",
    keyboardType: "default",
    name: "industry",
  },
  {
    title: "Logo",
    icon: "images-outline",
    placeholder: "Logo",
    uploadicon: true,
    name: "logo",
  },
  {
    title: "About Company",
    icon: "",
    placeholder: "Type..",
    keyboardType: "default",
    name: "landmark",
    text: true,
  },
];
